# Generated by Django 5.2.7 on 2025-10-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
    ]
