# Generated by Django 5.2.7 on 2025-10-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20251007_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercises',
        ),
    ]
