# Generated by Django 5.2.7 on 2025-10-07 23:07

import django.db.models.deletion
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(validators=[portal.models.validate_min])),
                ('reps', models.IntegerField(validators=[portal.models.validate_min])),
                ('position', models.CharField(max_length=255)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.exercise')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='programs',
            field=models.ManyToManyField(through='portal.Program', to='portal.exercise'),
        ),
    ]
