# Generated by Django 5.2.7 on 2025-10-11 00:33

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_program_patient_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(choices=[('HA', 'Wrist'), ('LE', 'Leg'), ('NE', 'Neck'), ('BA', 'Back'), ('FO', 'Foot'), ('SH', 'Shoulder'), ('AR', 'Arm'), ('GL', 'Glute'), ('CO', 'Core')], default='CO', max_length=2),
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('ST', 'Stretch'), ('SN', 'Strength'), ('CO', 'Condition'), ('BA', 'Balance'), ('OT', 'Other')], default='OT', max_length=255),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('DB', 'Dumbbells'), ('PB', 'Physioball'), ('ST', 'Strap'), ('TB', 'Theraband'), ('BK', 'Bike'), ('TM', 'Treadmill'), ('AW', 'Ankle Weight'), ('OT', 'Other'), ('NO', 'None')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.IntegerField(default=None, null=True, validators=[portal.models.validate_min]),
        ),
    ]
