# Generated by Django 5.2.7 on 2025-10-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_exercise_body_part_exercise_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='programs',
            field=models.ManyToManyField(related_name='patients', through='portal.Program', to='portal.exercise'),
        ),
        migrations.AlterField(
            model_name='program',
            name='position',
            field=models.CharField(choices=[('SU', 'Supine'), ('PR', 'Prone'), ('LA', 'Lateral'), ('ST', 'Standing'), ('SI', 'Sitting'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
