# Generated by Django 5.2.7 on 2025-10-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_patient_programs_alter_program_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(choices=[('HA', 'Wrist'), ('LE', 'Leg'), ('NE', 'Neck'), ('BA', 'Back'), ('FO', 'Foot'), ('SH', 'Shoulder'), ('AR', 'Arm'), ('GL', 'Glute'), ('CO', 'Core'), ('HI', 'Hip')], default='CO', max_length=2),
        ),
    ]
