# Generated by Django 5.2.7 on 2025-10-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_exercise_body_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(choices=[('DB', 'Dumbbells'), ('EB', 'Exercise Ball'), ('YB', 'Yoga Ball'), ('ST', 'Strap'), ('TB', 'Theraband'), ('BK', 'Bike'), ('TM', 'Treadmill'), ('AW', 'Ankle Weight'), ('OT', 'Other'), ('NO', 'None')], default='NO', max_length=2),
        ),
    ]
